In [6]:
import pandas as pd
import numpy as np
df = pd.read_csv('../data/raw/city_day.csv')
print(df.shape)
df.head()

(29531, 16)

,City,Date,PM2.5,PM10,NO,NO2,NOx,NH3,CO,SO2,O3,Benzene,Toluene,Xylene,AQI,AQI_Bucket
0,Ahmedabad,2015-01-01,NaN,NaN,0.92,18.22,17.15,NaN,0.92,27.64,133.36,0.00,0.02,0.00,NaN,NaN
1,Ahmedabad,2015-01-02,NaN,NaN,0.97,15.69,16.46,NaN,0.97,24.55,34.06,3.68,5.50,3.77,NaN,NaN
2,Ahmedabad,2015-01-03,NaN,NaN,17.40,19.30,29.70,NaN,17.40,29.07,30.70,6.80,16.40,2.25,NaN,NaN
3,Ahmedabad,2015-01-04,NaN,NaN,1.70,18.48,17.97,NaN,1.70,18.59,36.08,4.43,10.14,1.00,NaN,NaN
4,Ahmedabad,2015-01-05,NaN,NaN,22.10,21.42,37.76,NaN,22.10,39.33,39.31,7.01,18.89,2.78,NaN,NaN

In [8]:
print(df['City'].unique())

<StringArray>
[         'Ahmedabad',             'Aizawl',          'Amaravati',
           'Amritsar',          'Bengaluru',             'Bhopal',
       'Brajrajnagar',         'Chandigarh',            'Chennai',
         'Coimbatore',              'Delhi',          'Ernakulam',
           'Gurugram',           'Guwahati',          'Hyderabad',
             'Jaipur',         'Jorapokhar',              'Kochi',
            'Kolkata',            'Lucknow',             'Mumbai',
              'Patna',           'Shillong',            'Talcher',
 'Thiruvananthapuram',      'Visakhapatnam']
Length: 26, dtype: str

In [10]:
df_bengaluru = df[df['City'] == 'Bengaluru'].copy()
print(df_bengaluru.shape)

(2009, 16)

In [11]:
print(df_bengaluru['Date'].min())
print(df_bengaluru['Date'].max())

2015-01-01
2020-07-01

In [12]:
print(df_bengaluru.isnull().sum())

City             0
Date             0
PM2.5          146
PM10           360
NO               6
NO2              6
NOx              4
NH3            203
CO              11
SO2              6
O3             144
Benzene        266
Toluene         93
Xylene        2009
AQI             99
AQI_Bucket      99
dtype: int64

In [13]:
df_bengaluru['Date'] = pd.to_datetime(df_bengaluru['Date'])
df_bengaluru = df_bengaluru.sort_values('Date').reset_index(drop=True)

In [14]:
df_bengaluru = df_bengaluru.drop(columns=['Xylene', 'Benzene', 'Toluene', 'NH3', 'PM10'])

In [15]:
df_bengaluru = df_bengaluru.dropna(subset=['AQI'])
print(f"Rows remaining: {len(df_bengaluru)}")

Rows remaining: 1910

In [16]:
cols_to_fill = ['PM2.5', 'NO', 'NO2', 'NOx', 'CO', 'SO2', 'O3']
for col in cols_to_fill:
    df_bengaluru[col] = df_bengaluru[col].fillna(df_bengaluru[col].median())

print(df_bengaluru.isnull().sum())

City          0
Date          0
PM2.5         0
NO            0
NO2           0
NOx           0
CO            0
SO2           0
O3            0
AQI           0
AQI_Bucket    0
dtype: int64

In [17]:
df_bengaluru.to_csv('../data/processed/bengaluru_clean.csv', index=False)
print("Saved!")

Saved!

In [18]:
print(df_bengaluru.shape)
print(df_bengaluru.isnull().sum())
df_bengaluru.head()

(1910, 11)
City          0
Date          0
PM2.5         0
NO            0
NO2           0
NOx           0
CO            0
SO2           0
O3            0
AQI           0
AQI_Bucket    0
dtype: int64

,City,Date,PM2.5,NO,NO2,NOx,CO,SO2,O3,AQI,AQI_Bucket
79,Bengaluru,2015-03-21,48.59,3.47,27.00,18.04,3.89,1.94,52.96,91.0,Satisfactory
80,Bengaluru,2015-03-22,47.38,2.84,22.39,15.33,11.29,2.05,71.85,120.0,Moderate
81,Bengaluru,2015-03-23,65.65,3.10,26.35,17.45,9.95,6.30,72.84,154.0,Moderate
82,Bengaluru,2015-03-24,60.47,5.39,29.87,20.88,1.46,6.07,64.12,119.0,Moderate
83,Bengaluru,2015-03-25,62.56,3.16,23.57,16.39,10.05,4.98,82.34,232.0,Poor